### ISSUE TITLE
current code do not support edit, do the edit process need prompt2prompt attention replace editing? 

### ISSUE THREAD

**Issue by knightyxp** [wangkai930418/DPL#1]
Hello,

Real solid work!  but I noticed that the current code does not support editing. Would it be possible to release p2p edit code in the codebase? 

Thanks for considering this suggestion.

**Comment by wangkai930418** [comment]
> Hello,
> 
> Real solid work! but I noticed that the current code does not support editing. Would it be possible to release p2p edit code in the codebase?
> 
> Thanks for considering this suggestion.

Yes. I have the plan to totally update this repository after dealing with other stuffs in November and December. Will notice you once I finish them.
