### ISSUE TITLE
Query about the release of the images in figure 14 of the supplementary.pdf 

### ISSUE THREAD

**Issue by pipiofzl** [wangkai930418/DPL#2]
Dear authors,

Thanks for your ground-braking work, can you please release those input examples in figure 14 so that I can visualize the attention maps of them?

Thanks for your help in advance and look forward to your reply.

Best

**Comment by wangkai930418** [comment]
Hi, I updated some experimental images in google drive links which I showed over here:

https://github.com/wangkai930418/DPL?tab=readme-ov-file#todo

Hope that can help you.

**Comment by pipiofzl** [comment]
Hi, thanks for your rapid response!

Furthermore, I have three followup questions.
I noticed that there are files named p2p_edit.py and _4_image_edit.py. In these 2 files, there are comments stating that the code is based on pix2pix-zero. Thus, the first question I want to check is whether these 2 files are originated from pix2pix-zero.
Second, how can I use the output attention map from DPL on promp-to-prompt since the release of the promp-to-prompt-based cas was scheduled in December?
Last, are the captions used in DPL off-the-shlef from BLIP, that is, the prompt.txt is not mannually modified for better performance? I have run the release code on several examples, but DPL will fail on several cases where prompt.txt direct from _1_BLIP_caption.py. One possible reason is that the list does not contain BG since the terminal will show "no BG maps offered" error.
![image](https://github.com/wangkai930418/DPL/assets/87072615/6f6998bc-3dfe-4d75-8ae4-c7e4967631d8)


Thanks again and happy New Year!
Best

**Comment by wangkai930418** [comment]
Hi, to your questions:

1, Part of the codes (AttnStore) are from pix2pix-zero, not all codes are from them. You can check their repo also.

2, The output attention maps are just for visualization, I saved them in the .pkl file.

3, For some images, the BLIP-1 caption model cannot generate correct sentences. I modified them to make sure they are describing the input image correctly. The BLIP-2 model might be better, but it's released later than my paper. You can give it a try.

Best,

**Comment by pipiofzl** [comment]
Dear authors,

I have some problems about the images saved under the folders, first_recon and reconstruction, separately in the python file named _2_DDIM_inv.py. 

The first question is whether the image saved under the folder named first_recon is raw image since the raw image is transformed into latents and later reconstructed by decode_latents() in ddim_pipeline.py.

Second, is the method for reconstructing image saved under the reconstruction directory based on Null—text inversion?

Thanks for your help in advance and look forward to your reply.
Best

**Comment by wangkai930418** [comment]
1, If I remember it correctly, first_recon is the reconstruction with the first stage encoder&decoder of the Stable Diffusion. reconstruction is the folder from both the first stage encoder&decoder and the second stage inversion.

2, The DPL is applied with Null-Text inversion as we stated in the paper. DPL is used to have good attention maps and NTI is combined to learn null-text embedding to reconstruct the real images.

Best,

**Comment by pipiofzl** [comment]
Thanks a lot for your detailed answers!
