### ISSUE TITLE
 Are all these losses in the paper specific to the 16 feature map resolution？

### ISSUE THREAD

**Issue by Wenhao-Sun77** [wangkai930418/DPL#3]
Thank you for your outstanding work, I have a question for the paper, are all these losses in the paper specific to the 16 feature map resolution or are they summed over all resolutions?
<img width="662" alt="PixPin_2024-01-08_20-52-38" src="https://github.com/wangkai930418/DPL/assets/110756446/dcf4e97d-75c7-48c0-9336-e14b4956423b">

**Comment by wangkai930418** [comment]
Yes, all losses are applied to only the 16×16 attention maps as previous works indicates.

**Comment by Wenhao-Sun77** [comment]
> Yes, all losses are applied to only the 16×16 attention maps as previous works indicates.

Thank you for your reply! I visualize all the attention maps and found that only the 16x16 cross attention maps are more in line with human intuition and contain sufficient semantic information. That's part of the reason why the previous works and your work took this option, right?

**Comment by wangkai930418** [comment]
Yes. Previous works just say it works but didn't say why. We further did the verification.
