### ISSUE TITLE
Can you provide more details on the evaluation metrics?

### ISSUE THREAD

**Issue by HoiM** [wangkai930418/DPL#4]
I wonder how the clip-score and structure-dist are calcuated. Which clip model is used? Which layer's features of DINO is used?

**Comment by wangkai930418** [comment]
Hi, here are the information about the evaluations. 

DINO similarity: https://github.com/ShirAmir/dino-vit-features/blob/main/inspect_similarity.py
CLIP score: from torchmetrics.multimodal import CLIPScore

Best,
Kai.
