### ISSUE TITLE
A question about reproducing p2p

### ISSUE THREAD

**Issue by CostaliyA** [wangkai930418/DPL#5]
Thank you for a very good job! However, I encountered some problems when reproducing the p2p code. Can you show me how to combine dpl+p2p to achieve image editing?

**Comment by CostaliyA** [comment]
This is my reconstruction result of the example image:
<img width="256" alt="微信图片_20240515223818" src="https://github.com/wangkai930418/DPL/assets/128679540/4290d020-a078-409f-afed-52ec836347d1">

**Comment by wangkai930418** [comment]
Hi, that's too funny and strange. haha. Can you share with me how to get this? And there is another repo which is trying to reproducing.
https://github.com/RajatRasal/cxr-generation/tree/main/test/semantic_editing

**Comment by CostaliyA** [comment]
Of course, my code is below:### 1st step: get the background mask and inversion files for DPL
IMG_FORMAT='jpg'
IMG_FOLDER='images/'
FILE_NAME='catdog'

CUDA_VISIBLE_DEVICES=1 python _2_DDIM_inv.py \
    --input_image ${IMG_FOLDER}/${FILE_NAME}.${IMG_FORMAT} \
    --results_folder output/ \

### 2nd step: Dynamic Prompt Learning
PLACEHOLDER1='<cat-toy>'
PLACEHOLDER2='<dog-toy>'

INIT_TOKEN1='cat'
INIT_TOKEN2='dog'

MAX_ITER=0
LOSS='max'
ATTN_RES=16

ATTN=1.0
BG=0.05
COSINE=0.05

NULL_STEP=51
ATTN_STEP=21

al_ATTN=25.0 
al_BG=50.0
al_COSINE=25.0

be_ATTN=0.3
be_BG=0.7
be_COSINE=0.9
CUDA_VISIBLE_DEVICES=1 python _4_image_edit.py \
    --input_image ${IMG_FOLDER}/${FILE_NAME}.${IMG_FORMAT} \
    --results_folder output/${FILE_NAME}/ \
    --negative_guidance_scale 7.5 \
    --placeholder_token ${PLACEHOLDER1} ${PLACEHOLDER2}   \
    --initializer_token ${INIT_TOKEN1} ${INIT_TOKEN2}   \

**Comment by CostaliyA** [comment]
Of course, my code is as below:
`### 1st step: get the background mask and inversion files for DPL
IMG_FORMAT='jpg'
IMG_FOLDER='images/'
FILE_NAME='catdog'

CUDA_VISIBLE_DEVICES=1 python _2_DDIM_inv.py \
    --input_image ${IMG_FOLDER}/${FILE_NAME}.${IMG_FORMAT} \
    --results_folder output/ \

### 2nd step: Dynamic Prompt Learning
PLACEHOLDER1='<cat-toy>'
PLACEHOLDER2='<dog-toy>'

INIT_TOKEN1='cat'
INIT_TOKEN2='dog'

MAX_ITER=0
LOSS='max'
ATTN_RES=16

ATTN=1.0
BG=0.05
COSINE=0.05

NULL_STEP=51
ATTN_STEP=21

al_ATTN=25.0 
al_BG=50.0
al_COSINE=25.0

be_ATTN=0.3
be_BG=0.7
be_COSINE=0.9

CUDA_VISIBLE_DEVICES=0 python _3_dpl_inv.py \
    --input_image ${IMG_FOLDER}/${FILE_NAME}.${IMG_FORMAT} \
    --results_folder output/${FILE_NAME}/ \
    --negative_guidance_scale 7.5 \
    --null_inner_steps ${NULL_STEP} \
    --attn_inner_steps ${ATTN_STEP} \
    --lam_maxattn ${ATTN} \
    --lam_entropy ${BG} \
    --lam_cosine ${COSINE} \
    --print_freq 10 \
    --max_iter_to_alter ${MAX_ITER} \
    --placeholder_token ${PLACEHOLDER1} ${PLACEHOLDER2}   \
    --initializer_token ${INIT_TOKEN1} ${INIT_TOKEN2}   \
    --alpha_max  ${al_ATTN} \
    --alpha_ent  ${al_BG} \
    --alpha_cos  ${al_COSINE} \
    --beta_max  ${be_ATTN} \
    --beta_ent  ${be_BG} \
    --beta_cos  ${be_COSINE} \
    --loss_type ${LOSS} \
    --attn_res ${ATTN_RES} \
    --smooth_op \
    --softmax_op \
    --seg_dirs output/${FILE_NAME}/sd_study/ \
CUDA_VISIBLE_DEVICES=1 python _4_image_edit.py \
    --input_image ${IMG_FOLDER}/${FILE_NAME}.${IMG_FORMAT} \
    --results_folder output/${FILE_NAME}/ \
    --negative_guidance_scale 7.5 \
    --placeholder_token ${PLACEHOLDER1} ${PLACEHOLDER2}   \
    --initializer_token ${INIT_TOKEN1} ${INIT_TOKEN2}   \`
Moreover, I change the edit_prompt_str and postfix in _4_image_edit.py.I would appreciate it deeply if you could share your script or code.

**Comment by wangkai930418** [comment]
### 2nd step: Dynamic Prompt Learning
PLACEHOLDER1='<cat-toy>'
PLACEHOLDER2='<dog-toy>'

Did you write the placeholder? And can you show me the results of _3_dpl_inv.py? Especially the reconstruction results and cross-attention maps?

**Comment by wangkai930418** [comment]
If you have no problem in inversion and only encounter the reproducing issue in editing, check also my new script for editing here. I also made it through 2 weeks before.

https://github.com/wangkai930418/DPL/blob/main/docs/_4_image_edit.py

**Comment by CostaliyA** [comment]
> h

I have writen PLACEHOLDER1='cat-toy' and PLACEHOLDER2='dog-toy'with "<>".My cross attention visualization is 
![crossattn_ours_1 0_0 05_0 05_25 0_50 0_25 0_0 3_0 7_0 9_0](https://github.com/wangkai930418/DPL/assets/128679540/ba05f682-bfeb-448c-9f17-cf203466828e)
and my inversion result is 
![catdog](https://github.com/wangkai930418/DPL/assets/128679540/2f851995-6643-4574-9769-07fec2a047cb)

**Comment by CostaliyA** [comment]
Thank you for your reply!

**Comment by wangkai930418** [comment]
The cross attn is not too bad. But actually the saved reconstruction should be totally the same as the original image... The reconstruction is ensured by NTI.

**Comment by CostaliyA** [comment]
> The cross attn is not too bad. But actually the saved reconstruction should be totally the same as the original image... The reconstruction is ensured by NTI.

First_recon is right but the image in reconstruction is very strange。。。

**Comment by CostaliyA** [comment]
Moreover,it should be pointed out that - diffusers==0.21.0 does not match 'diffusers.models.cross_attention' and needs to be changed to diffusers.models.Attention. AND it works fine on another device：)Thank you for your kind reply~!

**Comment by wangkai930418** [comment]
Thanks! Will note that,,, I might do the wrong way that I test my code on one device and export the env yml on another one...

**Comment by CostaliyA** [comment]
Strange thing is same code and environment, rebuild is fine on V100 but wrong on A100 :D

**Comment by wangkai930418** [comment]
... Tell me your location. I'll join for A100...
